version: '2'

services:
  apollo-client:
    command: "yarn start"
    image: apollo-react-client:1
    build:
      dockerfile: docker/client/Dockerfile
      context: ./
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./client:/opt/app

  apollo-server:
    command: "yarn start"
    image: apollo-react-server:1
    build:
      dockerfile: docker/server/Dockerfile
      context: ./
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./server:/opt/app